name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build_memory_allocator
      run: |
        cd ./datastrutures
        make -C memory_cell/
    - name: build_datatype
      run: |
        cd ./datastrutures
        make -C datatype/
    - name: build_array
      run: |
        cd ./datastrutures
        make -C array/
    - name: build_linkedlist
      run: |
        cd ./datastrutures
        make -C linkedlist/
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: test_memory_allocator
      run: |
        cd ./datastrutures
        make -C memory_cell/ test-program
        echo "Running tests"
        memory_cell/test-program
    - name: test_datatype
      run: |
        echo "MISSING TESTS!!!"
    - name: test_array
      run: |
        cd ./datastrutures
        make -C array/ test-program
        echo "Running tests"
        array/test-program
    - name: test_linkedlist
      run: |
        cd ./datastrutures
        make -C linkedlist/ test-program
        echo "Running tests"
        linkedlist/test-program
